/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IFileData, } from "./components/bc-json-file-input/bc-json-file-input";
import { IFileData as IFileData1, } from "./components/bc-json-file-input/bc-json-file-input";
export namespace Components {
    interface BcJsonFileInput {
        "multiple": boolean;
        "objectToConsole": boolean;
        "previewJson": boolean;
    }
    interface BcJsonPreview {
        "objectToConsole": boolean;
        "previewList": ReadonlyArray<IFileData>;
    }
}
declare global {
    interface HTMLBcJsonFileInputElement extends Components.BcJsonFileInput, HTMLStencilElement {
    }
    var HTMLBcJsonFileInputElement: {
        prototype: HTMLBcJsonFileInputElement;
        new (): HTMLBcJsonFileInputElement;
    };
    interface HTMLBcJsonPreviewElement extends Components.BcJsonPreview, HTMLStencilElement {
    }
    var HTMLBcJsonPreviewElement: {
        prototype: HTMLBcJsonPreviewElement;
        new (): HTMLBcJsonPreviewElement;
    };
    interface HTMLElementTagNameMap {
        "bc-json-file-input": HTMLBcJsonFileInputElement;
        "bc-json-preview": HTMLBcJsonPreviewElement;
    }
}
declare namespace LocalJSX {
    interface BcJsonFileInput {
        "multiple"?: boolean;
        "objectToConsole"?: boolean;
        /**
          * Event emitted when files have been loaded
          * @type {EventEmitter<File[]>}
          * @memberof BcJsonFileInput
         */
        "onFilesLoaded"?: (event: CustomEvent<File[]>) => void;
        /**
          * Event emitted when files have been read (using FileReader)
          * @type {EventEmitter<IFileData[]>}
          * @memberof BcJsonFileInput
         */
        "onFilesRead"?: (event: CustomEvent<ReadonlyArray<IFileData>>) => void;
        "previewJson"?: boolean;
    }
    interface BcJsonPreview {
        "objectToConsole"?: boolean;
        "previewList"?: ReadonlyArray<IFileData>;
    }
    interface IntrinsicElements {
        "bc-json-file-input": BcJsonFileInput;
        "bc-json-preview": BcJsonPreview;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bc-json-file-input": LocalJSX.BcJsonFileInput & JSXBase.HTMLAttributes<HTMLBcJsonFileInputElement>;
            "bc-json-preview": LocalJSX.BcJsonPreview & JSXBase.HTMLAttributes<HTMLBcJsonPreviewElement>;
        }
    }
}
