/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BcJsonFileInput {
        "objectToConsole": boolean;
        "previewJson": boolean;
    }
    interface BcJsonPreview {
        "jsonString": string;
        "objectToConsole": boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLBcJsonFileInputElement extends Components.BcJsonFileInput, HTMLStencilElement {
    }
    var HTMLBcJsonFileInputElement: {
        prototype: HTMLBcJsonFileInputElement;
        new (): HTMLBcJsonFileInputElement;
    };
    interface HTMLBcJsonPreviewElement extends Components.BcJsonPreview, HTMLStencilElement {
    }
    var HTMLBcJsonPreviewElement: {
        prototype: HTMLBcJsonPreviewElement;
        new (): HTMLBcJsonPreviewElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "bc-json-file-input": HTMLBcJsonFileInputElement;
        "bc-json-preview": HTMLBcJsonPreviewElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface BcJsonFileInput {
        "objectToConsole"?: boolean;
        "onJsonLoad"?: (event: CustomEvent<string>) => void;
        "previewJson"?: boolean;
    }
    interface BcJsonPreview {
        "jsonString"?: string;
        "objectToConsole"?: boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "bc-json-file-input": BcJsonFileInput;
        "bc-json-preview": BcJsonPreview;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bc-json-file-input": LocalJSX.BcJsonFileInput & JSXBase.HTMLAttributes<HTMLBcJsonFileInputElement>;
            "bc-json-preview": LocalJSX.BcJsonPreview & JSXBase.HTMLAttributes<HTMLBcJsonPreviewElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
